[project]
name = "quantum-bank-bot"
version = "1.0.0"
description = "A Discord economy bot with advanced banking features, MongoDB integration, and colorful logging"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Quantum Bank Team"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Communications :: Chat",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "discord.py>=2.0.0",
    "motor>=3.0.0",
    "pymongo>=4.0.0",
    "python-dotenv>=0.19.0",
    "python-dateutil>=2.8.2",
    "asyncio>=3.4.3",
    "colorama>=0.4.4",
    "orjson>=3.6.0",
    "dnspython>=2.1.0",
    "aiohttp>=3.8.0",
    "cryptography>=36.0.0",
    "PyNaCl>=1.5.0",
    "typing-extensions>=4.0.0",
    "pytz>=2021.3",
]

[project.optional-dependencies]
high-performance = [
    'uvloop>=0.16.0; platform_system != "Windows"',
]

development = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.18.0",
    "pytest-cov>=3.0.0",
    "black>=22.1.0",
    "isort>=5.10.0",
    "ruff>=0.0.254",
    "pre-commit>=2.17.0",
    "mypy>=0.931",
]

docs = [
    "sphinx>=4.4.0",
    "sphinx-rtd-theme>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100
target-version = "py38"
extend-select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
]
extend-ignore = [
    "E203",  # whitespace before ':'
]

[tool.ruff.isort]
known-third-party = ["discord", "motor", "pymongo", "dotenv", "dateutil", "colorama", "orjson"]

[tool.black]
line-length = 100
target-version = ["py38"]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = ["discord.*", "motor.*", "pymongo.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
