name: Code Quality Checks

on:
  push:
    branches:
      - main
      - develop
      - ci/cd
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install linting tools
        run: |
          uv pip install ruff black isort mypy
      
      - name: Run linters
        run: |
          echo "Running black..."
          black --check .
          
          echo "Running isort..."
          isort --check .
          
          echo "Running ruff..."
          ruff .
          
          echo "Running mypy..."
          mypy . || echo "Type check issues found (non-blocking)"
