name: Code Quality Checks

on:
  push:
    branches:
      - main
      - build-pipelines
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install linting tools
        run: |
          uv pip install --system ruff black isort mypy
      
      - name: Run linters
        run: |
          echo "Running black..."
          # Run black in check mode but continue even if issues are found
          black --check . || echo "Warning: Black formatting issues found. This will not fail the build."
          
          echo "Running isort..."
          # Run isort in check mode but continue even if issues are found
          isort --check . || echo "Warning: Import sorting issues found. This will not fail the build."
          
          echo "Running ruff..."
          ruff . || echo "Warning: Ruff linting issues found. This will not fail the build."
          
          echo "Running mypy..."
          mypy . || echo "Type check issues found (non-blocking)"
