name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Verify dependencies
        run: |
          uv pip install --system -e .

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
          usedocker: false
          
      - name: Post-deployment checks
        run: |
          echo "Deployed successfully to Heroku"
          echo "App available at: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com" 