name: Deploy to Heroku
on:
  push:
    branches:
      - heroku-deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Login to Heroku Container
        uses: docker/login-action@v3
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}
          
      - name: Build and Push to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          
      - name: Health check
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          curl -f https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health || exit 1 
