name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Install dependencies with UV
      run: |
        uv pip install pytest pytest-asyncio pytest-cov
        uv pip install -e .
        # Create venv to make sure all dependencies are properly linked
        uv venv

    - name: Run tests
      run: |
        # Activate UV venv for better dependency resolution
        source .venv/bin/activate
        pytest tests/unit/ --cov=./ --cov-report=xml -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install UV and lint tools
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install ruff black isort

    - name: Install project with UV
      run: |
        uv pip install -e .

    - name: Lint with ruff
      run: |
        ruff check . --fix --ignore=ANN201,ANN001,ANN204,ANN202 --exclude tests/

    - name: Check formatting with black
      run: |
        black --check .

    - name: Check import sorting with isort
      run: |
        isort --check --profile black .

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          deny-licenses: GPL-3.0
          # Skip dependency diff since we're only using UV and pyproject.toml
          vulnerability-check: true
