name: Security Scan

on:
  push:
    branches:
      - main
      - build-pipelines
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Run security scans
        env:
          OPTIMIZATIONS_AVAILABLE: "true"
        run: |
          # Install dependencies with UV
          uv pip install --system safety bandit

          # Install project
          uv pip install -e . --system
          
          echo "Running safety check..."
          safety check --full-report || echo "Safety check found vulnerabilities"
          
          echo "Running bandit scan..."
          bandit -r . -x tests/ -f json -o bandit-results.json || echo "Bandit scan found issues"
      
      - name: Upload bandit results
        uses: actions/upload-artifact@v4
        with:
          name: bandit-results
          path: bandit-results.json
          retention-days: 7
      
      - name: Check for critical security issues
        run: |
          cat bandit-results.json | grep -q '"issue_severity": "HIGH"' && echo "✗ Critical security issues found!" || echo "✓ No critical security issues found"
